quiet: False
disable-version-string: True
with-expecter: True
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceNameSnake}}_mock.go"
dir: "mocks/{{.PackageName}}"
outpkg: "{{.PackageName}}mock"
packages:
  github.com/despondency/toggl-task/internal/persister:
  github.com/despondency/toggl-task/internal/service:
  github.com/despondency/toggl-task/internal/scanner:


