// Code generated by mockery. DO NOT EDIT.

package translatormock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Translator is an autogenerated mock type for the Translator type
type Translator struct {
	mock.Mock
}

type Translator_Expecter struct {
	mock *mock.Mock
}

func (_m *Translator) EXPECT() *Translator_Expecter {
	return &Translator_Expecter{mock: &_m.Mock}
}

// Translate provides a mock function with given fields: ctx, text, targetLanguage
func (_m *Translator) Translate(ctx context.Context, text string, targetLanguage string) (string, error) {
	ret := _m.Called(ctx, text, targetLanguage)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, text, targetLanguage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, text, targetLanguage)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, text, targetLanguage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Translator_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type Translator_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - targetLanguage string
func (_e *Translator_Expecter) Translate(ctx interface{}, text interface{}, targetLanguage interface{}) *Translator_Translate_Call {
	return &Translator_Translate_Call{Call: _e.mock.On("Translate", ctx, text, targetLanguage)}
}

func (_c *Translator_Translate_Call) Run(run func(ctx context.Context, text string, targetLanguage string)) *Translator_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Translator_Translate_Call) Return(_a0 string, _a1 error) *Translator_Translate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Translator_Translate_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *Translator_Translate_Call {
	_c.Call.Return(run)
	return _c
}

// NewTranslator creates a new instance of Translator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Translator {
	mock := &Translator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
